### ISSUE TITLE
Doesn't Seem to Work?

### ISSUE THREAD

**Issue by PerishBtw** [zatrit/mousebind#1]
I'm using the latest version of Lethal Company, V40.
I've installed this mod with BepInEx and LC_API
I'm unsure if I'm missing something but when I attempt to use my side mouse buttons it doesn't register for push to talk with mouse button 4 or 5. I've tried changing the "push to talk" button in settings, but just like vanilla Lethal Company, I cannot remap push to talk to a mouse button. Am I doing something wrong, or is this mod not currently working?

I'll include an image in-case I've done something wrong with my files.

![91698758884f02950f44cf87a0be92d2](https://github.com/zatrit/mousebind/assets/63642530/469df696-c112-40f5-bbc1-1aae22cae6e3)
![asfghjirfdtsgc](https://github.com/zatrit/mousebind/assets/63642530/673f4c72-8173-469d-8384-efcfbb451a8f)

**Comment by zatrit** [comment]
Just move content of MouseBind directory into game directory
